/**
 * All user-facing copy for the "About" page lives here so it can be edited
 * without touching the page layout. Edit the strings below — the page in
 * `page.tsx` just renders whatever is in these two arrays.
 *
 * - `SECTIONS`: the main text explaining how the app works. Each section has a
 *   heading and one or more paragraphs. Add/remove sections or paragraphs freely.
 * - `FAQS`: the expandable question/answer list at the bottom of the page.
 */

/** A titled block of body text in the main (non-FAQ) part of the page. */
export type AboutSection = {
  heading: string;
  /** Each string renders as its own paragraph. */
  paragraphs: string[];
};

/** One expandable entry in the FAQ section. */
export type Faq = {
  question: string;
  answer: string;
};

/** Short tagline shown under the page title. */
export const INTRO =
  "Momentum is a personal training app that helps you plan, generate, and log your workouts — with an AI coach that adapts to you.";

export const SECTIONS: AboutSection[] = [
  {
    heading: "What Momentum does",
    paragraphs: [
      "Momentum keeps your training in one place: build a long-term plan, generate individual workouts, and log every session so your progress stays visible.",
    ],
  },
  {
    heading: "Plans and workouts",
    paragraphs: [
      "In the Plan tab, the coach asks about your goals and schedule, then drafts a plan you can refine in a chat before saving — and reevaluate later as things change.",
      "When you're ready to train, the app can generate a single workout. It opens in the standard form, so you can tweak exercises, sets, and notes before committing.",
    ],
  },
  {
    heading: "Logging your training",
    paragraphs: [
      "Use Log workout to record what you did — pick exercises from the catalog or add your own, enter your sets, and totals like load and distance roll up automatically. Your history is always there to edit, re-date, or delete.",
    ],
  },
  {
    heading: "A note on the AI",
    paragraphs: [
      "Momentum's plans and workouts are generated by AI, which can be confidently wrong. Treat its suggestions as a starting point, not expert advice — review everything before you follow it, and check with a qualified professional for anything medical or safety-related.",
    ],
  },
];

export const FAQS: Faq[] = [
  {
    question: "What model is being used?",
    answer:
      "All aspects of the site currently use Opus 4.8. Eventually, I hope to allow users to choose between different models.",
  },
  {
    question: "I want to log an exercise that doesn't yet exist. How can I do this?",
    answer: "The 'coach' has the ability to create new exercise/workout types, so try asking there!",

  },
  {
    question: "What is included in prompts?",
    answer:
      "This varies with different parts of the site, but in general the agent has access to:\n- the information in your 'about me' section\n- a summary of your past few months of workouts\n- a detailed account of your past few workouts",
  },
  {
    question: "Who can see my data?",
    answer:
      "Only you. Every workout, plan, and chat is scoped to your account.",
  },
  {
    question: "Where can I make suggestions / look at the code?",
    answer:
      "You can view the code for the site [here](https://github.com/cjleggett/personal-trainer/tree/main) and open an issue with any suggestions!",
  },
  {
    question: "Who's paying for all these tokens?",
    answer:
      "Right now, I am. You can view an estimate of your individual token cost on the [usage page](https://momentumfitness.fun/usage), and if you start to feel bad about how much you're spending you can always reach out and ask for my Venmo!",
  },
];
